### ISSUE TITLE
extension incompatibility - beautiful lyrics by soCalifornian

### ISSUE THREAD

**Issue by WillFaray** [sanoojes/Spicetify-ShadeX#1]
### Do you have the latest versions of Spicetify, Spotify and ShadeX?

- [X] I'm using the latest versions of Spicetify, Spotify and ShadeX

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.44.405.g81fd6352
- Installed from: Spotify site
- Spicetify version: v2.37.7
- Color scheme: dark
- Extensions: beautiful lyrics, adblockify
- Custom apps: -
- ShadeX installation method: Spicetify Marketplace
```

### Description

Using ShadeX, the lyrics in the 'beautiful lyrics' extension do not appear

image 1 - the extension tab using shadex

image 2 - using another theme

### Screenshots

![image1](https://github.com/user-attachments/assets/c61518a0-3443-44ff-b988-834d99d13616)

![image2](https://github.com/user-attachments/assets/faa43b29-282d-4796-8b4e-6bb14d29f8cf)

**Comment by sanoojes** [comment]
Yes, this is a known issue. I apologize that it is not yet fixed, but I am unable to figure out the cause of the problem.

**Comment by sanoojes** [comment]
found out the issue 
it was caused by setting all buttons overflow to hidden 💀
i literally don't know why it broke the extension
